name: Tests

on:
  push:
    paths:
      - 'custom_components/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]

jobs:
  test-custom-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install Python dependencies
        run: |
          pipenv install

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pipenv run pytest tests/ -v --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration

